---
- name: Deploy Node.js Application
  hosts: all
  become: yes  # Run all tasks with sudo
  tasks:
    - include_role:
        name: server-setup

    - include_role:
        name: app
  vars:
    git_tag: "{{ git_tag }}"
